<?php
/**
 * @author <mdadalkhan@gmail.com>
 * @created_at: 18/02/2026
 * @updated_at: 18/02/2026
 * */
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class SeatsSeeder extends Seeder
{
    public function run(): void
    {
        $seats = [
    // Room 1 to 10
    ['room_id' => 1, 'seat_no' => '506A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 1, 'seat_no' => '506B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 2, 'seat_no' => '507A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 2, 'seat_no' => '507B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 3, 'seat_no' => '508A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 3, 'seat_no' => '508B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 4, 'seat_no' => '509A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 4, 'seat_no' => '509B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 5, 'seat_no' => '601A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 6, 'seat_no' => '602A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 7, 'seat_no' => '603A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 7, 'seat_no' => '603B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 8, 'seat_no' => '604A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 8, 'seat_no' => '604B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 9, 'seat_no' => '605A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 9, 'seat_no' => '605B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 10, 'seat_no' => '606A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 10, 'seat_no' => '606B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],

    // Room 11 to 20
    ['room_id' => 11, 'seat_no' => '607A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 11, 'seat_no' => '607B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 12, 'seat_no' => '608A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 12, 'seat_no' => '608B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 13, 'seat_no' => '609A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 13, 'seat_no' => '609B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 14, 'seat_no' => '610A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 14, 'seat_no' => '610B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 15, 'seat_no' => '701A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 15, 'seat_no' => '701B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 15, 'seat_no' => '701C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 16, 'seat_no' => '702A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 16, 'seat_no' => '702B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 16, 'seat_no' => '702C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 17, 'seat_no' => '703A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 17, 'seat_no' => '703B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 18, 'seat_no' => '704A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 18, 'seat_no' => '704B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 19, 'seat_no' => '705A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 19, 'seat_no' => '705B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 20, 'seat_no' => '706A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 20, 'seat_no' => '706B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],

    // Room 21 to 40
    ['room_id' => 21, 'seat_no' => '801A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 21, 'seat_no' => '801B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 21, 'seat_no' => '801C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 22, 'seat_no' => '802A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 22, 'seat_no' => '802B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 22, 'seat_no' => '802C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 23, 'seat_no' => '803A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 23, 'seat_no' => '803B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 24, 'seat_no' => '804A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 24, 'seat_no' => '804B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 25, 'seat_no' => '805A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 25, 'seat_no' => '805B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 26, 'seat_no' => '806A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 26, 'seat_no' => '806B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 27, 'seat_no' => '807A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 27, 'seat_no' => '807B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 27, 'seat_no' => '807C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 28, 'seat_no' => '808A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 28, 'seat_no' => '808B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 28, 'seat_no' => '808C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 29, 'seat_no' => '809A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 29, 'seat_no' => '809B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 29, 'seat_no' => '809C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 30, 'seat_no' => '810A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 30, 'seat_no' => '810B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 30, 'seat_no' => '810C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 31, 'seat_no' => '901A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 31, 'seat_no' => '901B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 31, 'seat_no' => '901C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 32, 'seat_no' => '902A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 32, 'seat_no' => '902B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 32, 'seat_no' => '902C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 33, 'seat_no' => '903A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 33, 'seat_no' => '903B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 34, 'seat_no' => '904A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 34, 'seat_no' => '904B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 35, 'seat_no' => '905A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 35, 'seat_no' => '905B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 36, 'seat_no' => '906A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 36, 'seat_no' => '906B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 37, 'seat_no' => '907A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 37, 'seat_no' => '907B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 37, 'seat_no' => '907C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 38, 'seat_no' => '908A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 38, 'seat_no' => '908B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 38, 'seat_no' => '908C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 39, 'seat_no' => '909A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 39, 'seat_no' => '909B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 39, 'seat_no' => '909C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 40, 'seat_no' => '910A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 40, 'seat_no' => '910B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 40, 'seat_no' => '910C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],

    // Room 41 to 60 (AC & VIP Mixed)
    ['room_id' => 41, 'seat_no' => '1001A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 41, 'seat_no' => '1001B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 41, 'seat_no' => '1001C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 42, 'seat_no' => '1002A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 42, 'seat_no' => '1002B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 42, 'seat_no' => '1002C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 43, 'seat_no' => '1003A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 43, 'seat_no' => '1003B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 44, 'seat_no' => '1004A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 44, 'seat_no' => '1004B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 45, 'seat_no' => '1005A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 45, 'seat_no' => '1005B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 46, 'seat_no' => '1006A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 46, 'seat_no' => '1006B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 47, 'seat_no' => '6001A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 47, 'seat_no' => '6001B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 48, 'seat_no' => '6002A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 48, 'seat_no' => '6002B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 49, 'seat_no' => '6003A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 49, 'seat_no' => '6003B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 49, 'seat_no' => '6003C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 49, 'seat_no' => '6003D', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 50, 'seat_no' => '6004A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 50, 'seat_no' => '6004B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 50, 'seat_no' => '6004C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 50, 'seat_no' => '6004D', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 51, 'seat_no' => '6005A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 51, 'seat_no' => '6005B', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 52, 'seat_no' => '6006A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 52, 'seat_no' => '6006B', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 53, 'seat_no' => '7001A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 53, 'seat_no' => '7001B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 54, 'seat_no' => '7002A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 54, 'seat_no' => '7002B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 55, 'seat_no' => '7003A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 55, 'seat_no' => '7003B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 55, 'seat_no' => '7003C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 55, 'seat_no' => '7003D', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 56, 'seat_no' => '7004A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 56, 'seat_no' => '7004B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 56, 'seat_no' => '7004C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 56, 'seat_no' => '7004D', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 57, 'seat_no' => '7005A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 57, 'seat_no' => '7005B', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 58, 'seat_no' => '7006A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 58, 'seat_no' => '7006B', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 59, 'seat_no' => '8001A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 59, 'seat_no' => '8001B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 60, 'seat_no' => '8002A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 60, 'seat_no' => '8002B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],

    // Room 61 to end
    ['room_id' => 61, 'seat_no' => '8003A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 61, 'seat_no' => '8003B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 61, 'seat_no' => '8003C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 61, 'seat_no' => '8003D', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 62, 'seat_no' => '8004A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 62, 'seat_no' => '8004B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 62, 'seat_no' => '8004C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 62, 'seat_no' => '8004D', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 63, 'seat_no' => '8005A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 63, 'seat_no' => '8005B', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 64, 'seat_no' => '8006A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 64, 'seat_no' => '8006B', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 65, 'seat_no' => '9001A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 65, 'seat_no' => '9001B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 66, 'seat_no' => '9002A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 66, 'seat_no' => '9002B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 67, 'seat_no' => '9003A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 67, 'seat_no' => '9003B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 67, 'seat_no' => '9003C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 67, 'seat_no' => '9003D', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 68, 'seat_no' => '9004A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 68, 'seat_no' => '9004B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 68, 'seat_no' => '9004C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 68, 'seat_no' => '9004D', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 69, 'seat_no' => '9005A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 69, 'seat_no' => '9005B', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 70, 'seat_no' => '9006A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 70, 'seat_no' => '9006B', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 71, 'seat_no' => '9007A', 'type' => 'normal', 'rent' => 180, 'status' => 'available'],
    ['room_id' => 72, 'seat_no' => '10001A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 72, 'seat_no' => '10001B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 73, 'seat_no' => '10002A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 73, 'seat_no' => '10002B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 74, 'seat_no' => '10003A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 74, 'seat_no' => '10003B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 74, 'seat_no' => '10003C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 74, 'seat_no' => '10003D', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 75, 'seat_no' => '10004A', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 75, 'seat_no' => '10004B', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 75, 'seat_no' => '10004C', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 75, 'seat_no' => '10004D', 'type' => 'ac', 'rent' => 375, 'status' => 'available'],
    ['room_id' => 76, 'seat_no' => '10005A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 76, 'seat_no' => '10005B', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 77, 'seat_no' => '10006A', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 77, 'seat_no' => '10006B', 'type' => 'vip', 'rent' => 815, 'status' => 'available'],
    ['room_id' => 78, 'seat_no' => '10007A', 'type' => 'normal', 'rent' => 180, 'status' => 'available'],
];
      $finalData = array_map(function($seat) {
        $seat['created_at'] = now();
        $seat['updated_at'] = now();
        return $seat;
    }, $seats);
      
      DB::table('seats')->insert($finalData);
    }
}
